import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import "../globals.css"
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // https://github.com/shadcn-ui/ui/issues/977
  return (
    <ClerkProvider >
      <html lang="en">
        <body className='flex flex-col'>
          <Header />
          <div className='container max-w-5xl mt-20 pb-5'>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
